# Generated by Django 4.1.3 on 2022-11-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_sensors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='Sensors',
        ),
    ]
